import {
  Geist,
  Geist_Mono,
  Roboto_Slab,
  Lexend,
  Playfair_Display,
} from "next/font/google";

import "./globals.css";
import Navbar from "@/components/layouts/navbar/navbar";
import { Providers } from "./Provider";
// import ProviderTheme from "app/ProviderTheme";
import Slider from "@/components/shared/Slider";
import Footer from "@/components/layouts/navbar/Footer/Footer";
// import { ThemeProvider } from "@mui/material";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const robotoSlab = Roboto_Slab({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // dizayna uyğun olaraq seç
  variable: "--font-roboto-slab", // optional CSS variable
  display: "swap", // fonts yüklənərkən fallback göstərilsin
});

const lexend = Lexend({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // dizayna uyğun olaraq seç
  variable: "--font-lexend", // optional CSS variable
  display: "swap", // fonts yüklənərkən fallback göstərilsin
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfair_Display = Playfair_Display({
  variable: "--playfair_Display",
  subsets: ["latin"],
});

export const metadata = {
  title: "Elşən İsmayılov",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // <ProviderTheme>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${robotoSlab.variable} ${lexend.variable} ${playfair_Display.variable}`}
        style={{ backgroundColor: "#f0edea" }}
      >
        <Providers>
          <Navbar />
          <Slider />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
    // {/* </ProviderTheme> */}
  );
}
